# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

# Let us list the factors of the first seven triangle numbers:

#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.

# What is the value of the first triangle number to have over five hundred divisors?

triangle_value = 1
count = 2
divisors = 1

def get_factors(number)
	factors = []
	for i in 1..(number**0.5)
		if number % i == 0
			factors << i
			factors << number/i
		end
	end
	return factors.length
end

while divisors < 500
	divisors = get_factors(triangle_value)
	puts "#{triangle_value}: #{divisors}"
	if divisors >= 500
		break
	else
		triangle_value += count
		count += 1
	end
end

